# Generated by Django 4.2.30 on 2026-08-03 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_sistema', '0001_initial'),
        ('ventas', '0002_venta_block_number_venta_cuenta_blockchain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='COMPLETADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_sistema.usuariosistema'),
        ),
    ]
