# Generated by Django 4.2.30 on 2026-08-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_estado_alter_venta_numero_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(blank=True, default='Consumidor Final', max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='RegistroBlockchainVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('VENTA', 'Venta original'), ('ANULACION_VENTA', 'Anulación'), ('CORRECCION_VENTA', 'Venta corregida')], max_length=30)),
                ('referencia', models.CharField(max_length=150)),
                ('referencia_original', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(default='Administrador', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='VERIFICADO', max_length=30)),
                ('hash_operacion', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_blockchain', models.CharField(blank=True, max_length=100, null=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_blockchain', to='ventas.venta')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
