# Generated by Django 4.2.30 on 2026-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('Compras', 'Compras'), ('Ventas', 'Ventas'), ('Inventario', 'Inventario'), ('General', 'General')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
    ]
