# Generated by Django 4.2.30 on 2026-07-19 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='stock_actual',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='estado',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='laboratorio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamentos',
        ),
    ]
