# Generated by Django 4.2.30 on 2026-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='RECIBIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
