# Generated by Django 4.2.30 on 2026-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_estado_compra_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta_blockchain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='hash_operacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
