# Generated by Django 4.2.30 on 2026-08-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_block_number_compra_cuenta_blockchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra original'), ('ANULACION_COMPRA', 'Anulación'), ('CORRECCION_COMPRA', 'Compra corregida'), ('VENTA', 'Venta original'), ('ANULACION_VENTA', 'Anulación de venta'), ('CORRECCION_VENTA', 'Venta corregida')], max_length=30)),
                ('referencia', models.CharField(max_length=150)),
                ('referencia_original', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(default='Administrador', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='VERIFICADO', max_length=30)),
                ('hash_operacion', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_blockchain', models.CharField(blank=True, max_length=100, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_blockchain', to='compras.compra')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
